import = ["/home/mkaltw/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[selection]
save_to_clipboard = true

[window]
opacity = 1.0
title = "Alacritty"
